// MODAL
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';

// MENU
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';
export const START_FETCHING_MENU = 'START_FETCHING_MENU';
export const END_FETCHING_MENU = 'END_FETCHING_MENU';

// ITEM
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';
export const START_FETCHING_ITEM = 'START_FETCHING_ITEM';
export const END_FETCHING_ITEM = 'END_FETCHING_ITEM';

// CART
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const SET_ITEM_DATA = 'SET_ITEM_DATA';
export const SET_MODIFIER_DATA = 'SET_MODIFIER_DATA';
export const START_FETCHING_CART_DATA = 'START_FETCHING_CART_DATA';
export const END_FETCHING_CART_DATA = 'END_FETCHING_CART_DATA';
export const SET_COUPON_TO_CART = 'SET_COUPON_TO_CART';
export const SET_SHOP_TO_CART = 'SET_SHOP_TO_CART';
export const SET_ORDER_TYPE_TO_CART = 'SET_ORDER_TYPE_TO_CART';
export const SET_CONTACT_INFO_TO_CART = 'SET_CONTACT_INFO_TO_CART';
export const SET_CURRENT_STEP_TO_CART = 'SET_CURRENT_STEP_TO_CART';
export const SET_PHONE_VERIFIED_TO_CART = 'SET_PHONE_VERIFIED_TO_CART';
export const COMPLETE_CART_CHECKOUT = 'COMPLETE_CART_CHECKOUT';

// SHOP
export const FETCH_SHOP_SUCCESS = 'FETCH_SHOP_SUCCESS';
export const FETCH_SHOP_FAILURE = 'FETCH_SHOP_FAILURE';

// MODIFIER MODALS
export const SET_MODIFIER_MODAL_DATA = 'SET_MODIFIER_MODAL_DATA';

// COUPON MODALS
export const CHECK_COUPON_MODAL_CODE_SUCCESS = 'CHECK_COUPON_MODAL_CODE_SUCCESS';
export const CHECK_COUPON_MODAL_CODE_FAILURE = 'CHECK_COUPON_MODAL_CODE_FAILURE';

// VERIFY
export const VERIFY_PHONE_SUCCESS_ORDERING = 'VERIFY_PHONE_SUCCESS_ORDERING';
export const VERIFY_PHONE_ERROR_VERIFY = 'VERIFY_PHONE_ERROR_VERIFY';
export const VERIFY_PHONE_ERROR_REPHONENUMBER = 'VERIFY_PHONE_ERROR_REPHONENUMBER';

export const VERIFY_CODE_SUCCESS_ORDERING = 'VERIFY_CODE_SUCCESS_ORDERING';
export const VERIFY_CODE_ERROR_REVERIFY = 'VERIFY_CODE_ERROR_REVERIFY';
export const VERIFY_CODE_ERROR_REPHONENUMBER = 'VERIFY_CODE_ERROR_REPHONENUMBER';

export const SET_VERIFY_DATA = 'SET_VERIFY_DATA';
export const SET_CURRENT_CART_TO_VERIFY = 'SET_CURRENT_CART_TO_VERIFY';
