export const CHECK_OUT_PENDING_STEP = 'CHECK_OUT_PENDING_STEP';
export const CHECK_OUT_SELECT_LOCATION_STEP = 'CHECK_OUT_SELECT_LOCATION_STEP';
export const CHECK_OUT_SELECT_ORDER_TYPE_STEP = 'CHECK_OUT_SELECT_ORDER_TYPE_STEP';
export const CHECK_OUT_COMPLETED_STEP = 'CHECK_OUT_COMPLETED_STEP';
